#!/usr/bin/env bash
#
# Installs dotfiles
# Globals: None
# Arguments: None
# Returns: None

readonly SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

# Backups, if exists, and creates symbolic link of file.
# Globals: None
# Arguments:
#   1: destination file
#   2: source file
# Returns: None
_link_file() {
  [[ -e "$1" && ! -L "$1" ]] && mv "$1" "$1.$(date '+%Y%m%d%H%M%S')"
  [[ -L "$1" ]] && rm -f "$1"
  ln -s "$2" "$1"  
}

# install brew bundle
[[ "$(uname)" == "Darwin" ]] \
  && command -v brew &>/dev/null \
  && { cd "$SELF_DIR" && brew bundle install ; }

# install vim-plug
curl -sfLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[[ ! -d "$HOME/.config" ]] && mkdir -p "$HOME/.config"

# link dotfiles
case "$SHELL" in
 */bash)
  _link_file "$HOME/.bashrc" "$SELF_DIR/bash/bashrc.symlink"
  _link_file "$HOME/.bash_profile" "$SELF_DIR/bash/bash_profile.symlink"
  _link_file "$HOME/.bash_profile.d" "$SELF_DIR/bash/bash_profile.d.symlink"
  _link_file "$HOME/.liquid.ps1" "$SELF_DIR/bash/liquid.ps1.symlink"
  ;;
 */zsh)
  echo "TODO"
  ;;
esac
_link_file "$HOME/bin" "$SELF_DIR/bin.symlink"
_link_file "$HOME/.config/git" "$SELF_DIR/config.git.symlink"
_link_file "$HOME/.vimrc" "$SELF_DIR/vimrc.symlink"
touch "$SELF_DIR/config.git.symlink/config.custom"
