#!/usr/bin/env bash
# 
# Fetches certificate information from specified hostname
# Globals: None
# Arguments:
#   1: hostname (required)
# Returns:
#   Certificate information
! command -v openssl &>/dev/null && echo "[error] openssl binary not found" && exit 1
usage="usage: show-cert <hostname> [servername]"
[[ -z "$1" ]] && echo "[error] argument <hostname> missing or empty" && echo "$usage" && exit 1
echo \
  | openssl s_client -showcerts -servername "${2:-$1}" -connect "$1:443" 2>/dev/null \
  | openssl x509 -inform pem -noout -text